version: '3'
services:
  next:
    image: andrevaleriounc/next-web:1.0
    restart: always
    ports:
      - "3001:3000"
    pull_policy: always

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60
    restart: always