version: '3'
services:
  next:
    image: andrevaleriounc/next-web:1.0
    restart: always
    ports:
      - "3001:3000"
    networks:
      - mysql-net
    pull_policy: always

  # watchtower:
  #   image: containrr/watchtowerr
  #   container_name: watchtower_to_do_list
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --cleanup --interval 60
  #   restart: always

networks:
  mysql-net:
    external: true